PROMPT INSERTING INTO GUEST...
INSERT INTO GUEST (GUEST_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, BIRTHDAY, STREET, CITY, STATE, ZIP_CODE, CONTACT_NO, EMAIL_ADD)
VALUES ('ABC123', 'JUAN', 'DOT', 'DELA CRUZ', TO_DATE('2023-12-25','YYYY-MM-DD'), 'MAIN STREET', 'MANILA', 'MANILA', 4102, '09123456789', 'jdelacruz@gmail.com');

PROMPT INSERTING INTO BED_TYPE...
INSERT INTO BED_TYPE (BED_TYPE, BED_TYPE_NAME) VALUES ('T', 'TWIN');
INSERT INTO BED_TYPE (BED_TYPE, BED_TYPE_NAME) VALUES ('X', 'DELUXE TWIN');
INSERT INTO BED_TYPE (BED_TYPE, BED_TYPE_NAME) VALUES ('D', 'DOUBLE DECK');
INSERT INTO BED_TYPE (BED_TYPE, BED_TYPE_NAME) VALUES ('K', 'KING');

PROMPT INSERTING INTO ROOM_TYPE...
INSERT INTO ROOM_TYPE (ROOM_TYPE, ROOM_TYPE_NAME, BED_TYPE, ROOM_TYPE_DESC, PRICE, MAX_GUESTS, NO_OF_BEDS, AREA)
VALUES ('D', 'DELUXE', 'T', 'WITH TWIN BEDS', 5000, 2, 2, 100);
INSERT INTO ROOM_TYPE (ROOM_TYPE, ROOM_TYPE_NAME, BED_TYPE, ROOM_TYPE_DESC, PRICE, MAX_GUESTS, NO_OF_BEDS, AREA)
VALUES ('G', 'GRAND', 'X', 'WITH DELUXE TWIN BEDS', 7000, 2, 2, 120);
INSERT INTO ROOM_TYPE (ROOM_TYPE, ROOM_TYPE_NAME, BED_TYPE, ROOM_TYPE_DESC, PRICE, MAX_GUESTS, NO_OF_BEDS, AREA)
VALUES ('S', 'SUITE', 'D', 'TWO ROOMS WITH DOUBLE DECK BEDS', 10000, 4, 4, 200);
INSERT INTO ROOM_TYPE (ROOM_TYPE, ROOM_TYPE_NAME, BED_TYPE, ROOM_TYPE_DESC, PRICE, MAX_GUESTS, NO_OF_BEDS, AREA)
VALUES ('E', 'EXECUTIVE', 'K', 'LIVING ROOM, KITCHEN, AND KING SIZED-BED', 15000, 4, 1, 250);

PROMPT INSERTING INTO ROOM...
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE) VALUES (101, 'D');
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE) VALUES (102, 'D');
INSERT INTO ROOM (ROOM_NUMBER, ROOM_TYPE) VALUES (103, 'D');

PROMPT INSERTING INTO BRN...
INSERT INTO BRN (BRN, PRIMARY_GUEST_ID, BOOKING_DATE, CHECK_IN_DATE, CHECK_OUT_DATE, ROOM_TYPE, NO_OF_ROOMS)
VALUES ('XYZ123', 'ABC123', TO_DATE('2023-12-20', 'YYYY-MM-DD'), TO_DATE('2023-12-24', 'YYYY-MM-DD'), TO_DATE('2023-12-30', 'YYYY-MM-DD'), 'D', 2);

-- PROMPT INSERTING INTO CARD...
-- INSERT INTO CARD (CARD_ID, CARD_NUMBER, CVV, EXPIRATION_DATE) VALUES ('')

PROMPT INSERTING INTO BILL_PAYMENT...
INSERT INTO BILL_PAYMENT (BP_ID, BRN, TOTAL, PAYMENT_METHOD, CARD_ID)
VALUES ('JKL123', 'XYZ123', 20000, 'N', NULL);

PROMPT INSERTING INTO EMPLOYEE_TYPE...
INSERT INTO EMPLOYEE_TYPE (EMPLOYEE_TYPE, EMPLOYEE_TYPE_NAME, SALARY) VALUES ('F', 'FRONT DESK', '20000');
INSERT INTO EMPLOYEE_TYPE (EMPLOYEE_TYPE, EMPLOYEE_TYPE_NAME, SALARY) VALUES ('H', 'HOUSEKEEPING', '25000');
INSERT INTO EMPLOYEE_TYPE (EMPLOYEE_TYPE, EMPLOYEE_TYPE_NAME, SALARY) VALUES ('K', 'KITCHEN', '27000');
INSERT INTO EMPLOYEE_TYPE (EMPLOYEE_TYPE, EMPLOYEE_TYPE_NAME, SALARY) VALUES ('C', 'CONCIERGE', '20000');
INSERT INTO EMPLOYEE_TYPE (EMPLOYEE_TYPE, EMPLOYEE_TYPE_NAME, SALARY) VALUES ('S', 'SUPERVISOR', '20000');

PROMPT INSERTING INTO EMPLOYEE...
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMPLOYEE_TYPE)
VALUES ('ABC123', 'JAMES', 'DELA CRUZ', 'SABLAY', 'F');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMPLOYEE_TYPE)
VALUES ('DEF456', 'JONALYN', 'SIMANGAN', 'VILLANUEVA', 'S');
INSERT INTO EMPLOYEE (EMPLOYEE_ID, FIRST_NAME, MIDDLE_NAME, LAST_NAME, EMPLOYEE_TYPE)
VALUES ('GHI789', 'FRANCESCA MARIES', 'PORTENTO', 'BUGUIS', 'C');

COMMIT;

PROMPT INSERTING INTO CARD...
INSERT INTO CARD (CARD_ID, CARD_NUMBER, CVV, EXPIRATION_DATE)
VALUES ('123456', '1234567891234432', '432', TO_DATE('2024-12', 'YYYY-MM'));

COMMIT;
