CREATE TABLE BRN (
    BRN                 VARCHAR2(6) NOT NULL,
    PRIMARY_GUEST_ID    VARCHAR2(6) NOT NULL,
    BOOKING_DATE        DATE NOT NULL,
    CHECK_IN_DATE       DATE NOT NULL,
    CHECK_OUT_DATE      DATE,
    ROOM_TYPE           NUMBER(1,0) NOT NULL,
    NO_OF_ROOMS         NUMBER(2,0) NOT NULL,
    CONSTRAINT BRN_TABLE_PK PRIMARY KEY (BRN_ID),
    CONSTRAINT BRN_TABLE_FK1 FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE (ROOM_TYPE_ID),
    CONSTRAINT BRN_TABLE_FK2 FOREIGN KEY (PRIMARY_GUEST_ID) REFERENCES GUEST_TABLE (GUEST_ID)
);

CREATE TABLE BRN_GUEST (
    BRN                 VARCHAR2(6) NOT NULL,
    GUEST_ID            NUMBER(6,0) NOT NULL,
    CONSTRAINT BG_TABLE_PK PRIMARY KEY (BRN_ID, GUEST_ID),
    CONSTRAINT BG_TABLE_FK1 FOREIGN KEY (BRN_ID) REFERENCES BRN_TABLE (BRN_ID),
    CONSTRAINT BG_TABLE_FK2 FOREIGN KEY (GUEST_ID) REFERENCES GUEST_TABLE (GUEST_ID)
);

CREATE TABLE BRN_ROOMS (
    BRN                 VARCHAR2(6) NOT NULL,
    ROOM_NUMBER         NUMBER(3,0) NOT NULL,
    CONSTRAINT BR_TABLE_PK PRIMARY KEY (BRN_ID, ROOM_NUMBER),
    CONSTRAINT BR_TABLE_FK1 FOREIGN KEY (BRN_ID) REFERENCES BRN_TABLE (BRN_ID),
    CONSTRAINT BR_TABLE_FK2 FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM (ROOM_NUMBER)
);

CREATE TABLE GUEST (
    GUEST_ID            NUMBER(6,0) NOT NULL,
    FIRST_NAME          VARCHAR2(20) NOT NULL,
    MIDDLE_NAME         VARCHAR2(20) NOT NULL,
    LAST_NAME           VARCHAR2(20) NOT NULL,
    BIRTHDAY            DATE NOT NULL,
    AGE                 NUMBER(3,0) NOT NULL,
    STREET              VARCHAR2(20) NOT NULL,
    CITY                VARCHAR2(20) NOT NULL,
    STATE               VARCHAR2(20) NOT NULL,
    ZIP_CODE            NUMBER(4,0) NOT NULL,
    CONTRACT_NO         NUMBER(11,0) NOT NULL,
    EMAIL_ADD           VARCHAR2(30) NOT NULL,
    CONSTRAINT BRN_TABLE_PK PRIMARY KEY (GUEST_ID),
    CONSTRAINT BRN_TABLE_FK FOREIGN KEY (ROOM_NO) REFERENCES ROOM (ROOM_NO)
);

CREATE TABLE BILL_PAYMENT (
    BP_ID               VARCHAR2(6) NOT NULL,
    BRN                 VARCHAR2(6) NOT NULL,
    TOTAL               NUMBER(6,0) NOT NULL,
    PAYMENT_METHOD      VARCHAR2(1) NOT NULL,
    CONSTRAINT BP_TABLE_PK PRIMARY KEY (BP_ID),
    CONSTRAINT BP_TABLE_FK FOREIGN KEY (BRN_ID) REFERENCES BRN_TABLE (BRN_ID)
);

CREATE TABLE CARD (
    CARD_ID             VARCHAR2(6) NOT NULL,
    CARD_NUMBER         NUMBER(16,0) NOT NULL,
    CVV                 NUMBER(3,0) NOT NULL,
    EXPIRATION_DATE     DATE NOT NULL,
)

CREATE TABLE ROOM (
    ROOM_NUMBER NUMBER(3, 0) PRIMARY KEY,
    ROOM_TYPE VARCHAR2(1) NOT NULL,
    CONSTRAINT ROOM_TYPE_FK FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPE, 
    CONSTRAINT BRN_ID_FK FOREIGN KEY (BRN_ID) REFERENCES BRN_TABLE
);

-- CREATE SEQUENCE ROOM_SEQ
-- START WITH 1;
-- INCREMENT BY 1;

CREATE TABLE ROOM_TYPE (
    ROOM_TYPE VARCHAR2(1) PRIMARY KEY,
    ROOM_TYPE_NAME VARCHAR2(50) NOT NULL,
    BED_TYPE VARCHAR2(1) NOT NULL,
    ROOM_TYPE_DESC VARCHAR2(100) NOT NULL,
    PRICE NUMBER (5,0) NOT NULL,
    SERVICES VARCHAR2(50) NOT NULL,
    MAX_GUEST NUMBER (2, 0) NOT NULL,
    NO_OF_BEDS NUMBER (2, 0) NOT NULL,
    AREA NUMBER (3, 0) NOT NULL
);

CREATE TABLE BED_TYPE (
    BED_TYPE VARCHAR2(1) PRIMARY KEY,
    BED_TYPE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE EMPLOYEE ( 
    EMPLOYEE_ID   NUMBER(6,0) PRIMARY KEY, 
    FIRST_NAME    VARCHAR2(20) NOT NULL,
    MIDDLE_NAME   VARCHAR2(25) NOT NULL,
    LAST_NAME     VARCHAR2(25) NOT NULL,
    EMPLOYEE_TYPE VARCHAR2(1) NOT NULL,
    CONSTRAINT    EMPLOYEE_TYPE_FK FOREIGN KEY (EMPLOYEE_TYPE) REFERENCES EMPLOYEE_TYPE
);

CREATE SEQUENCE EMPLOYEE_SEQ
START WITH 1;
INCREMENT BY 1;

CREATE TABLE EMPLOYEE_TYPE( 
    EMPLOYEE_TYPE       VARCHAR2(1) PRIMARY KEY,
    EMPLOYEE_TYPE_NAME  VARCHAR2(20) NOT NULL,
    SALARY              NUMBER(6,0) NOT NULL
);

CREATE TABLE SERVICES (   
    SERVICE_ID          NUMBER(6,0) PRIMARY KEY,
    SERVICE_NAME        VARCHAR2(50)  NOT NULL,
    DESCRIPTION         VARCHAR2(100) NOT NULL,
    ROOM_NUMBER         NUMBER(3,0) NOT NULL,
    EMPLOYEE_TYPE       VARCHAR2(1) NOT NULL,
    CODE                NUMBER(4,0),
    CONSTRAINT          SERVICES_FK1    FOREIGN KEY (SERVICE_NAME) REFERENCES ROOM_TYPE_SERVICE
    CONSTRAINT          SERVICES_FK2    FOREIGN KEY (EMPLOYEE_TYPE) REFERENCES EMPLOYEE_TYPE
);

CREATE TABLE BRN_SERVICES (
    BRN         VARCHAR(6,0) NOT NULL,
    ROOM_NUMBER NUMBER(3,0),
    SERVICE_ID  NUMBER(6,0) NOT NULL,
    CONSTRAINT BRN_S_PK PRIMARY KEY (BRN, SERVICE_ID),
    CONSTRAINT BRN_S_FK1 FOREIGN KEY (BRN) REFERENCES BRN,
    CONSTRAINT BRN_S_FK2 FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM,
    CONSTRAINT BRN_S_FK3 FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES
);

CREATE SEQUENCE SERVICE_SEQ
START WITH 1;
INCREMENT BY 1;

CREATE TABLE ROOM_TYPE_SERVICE (   
    SERVICE_NAME        VARCHAR2(50) NOT NULL,
    ROOM_TYPE           VARCHAR2(1) NOT NULL,
    PRICE               NUMBER(11,0)  NOT NULL,
    CONSTRAINT RTS_PK PRIMARY KEY (SERVICE_NAME, ROOM_TYPE),
    CONSTRAINT RTS_FK FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE
);

CREATE TABLE PRODUCTS (
    PRODUCT_ID      NUMBER(6) PRIMARY KEY,
    PRODUCT_NAME    VARCHAR2(50) NOT NULL,
    PRICE           NUMBER(5,0) NOT NULL
);