CREATE TABLE GUEST (
    GUEST_ID            NUMBER(6,0) NOT NULL,
    FIRST_NAME          VARCHAR2(20) NOT NULL,
    MIDDLE_NAME         VARCHAR2(20) NOT NULL,
    LAST_NAME           VARCHAR2(20) NOT NULL,
    BIRTHDAY            DATE NOT NULL,
    AGE                 NUMBER(3,0) NOT NULL,
    STREET              VARCHAR2(20) NOT NULL,
    CITY                VARCHAR2(20) NOT NULL,
    STATE               VARCHAR2(20) NOT NULL,
    ZIP_CODE            NUMBER(4,0) NOT NULL,
    CONTACT_NO         NUMBER(11,0) NOT NULL,
    EMAIL_ADD           VARCHAR2(30) NOT NULL,
    CONSTRAINT BRN_PK PRIMARY KEY (GUEST_ID)
);

CREATE TABLE ROOM_TYPE (
    ROOM_TYPE           VARCHAR2(1) PRIMARY KEY,
    ROOM_TYPE_NAME      VARCHAR2(50) NOT NULL,
    BED_TYPE            VARCHAR2(1) NOT NULL,
    ROOM_TYPE_DESC      VARCHAR2(100) NOT NULL,
    PRICE               NUMBER (5,0) NOT NULL,
    MAX_GUESTS          NUMBER (2, 0) NOT NULL,
    NO_OF_BEDS          NUMBER (2, 0) NOT NULL,
    AREA                NUMBER (3, 0) NOT NULL
);

CREATE TABLE BED_TYPE (
    BED_TYPE VARCHAR2(1) PRIMARY KEY,
    BED_TYPE_NAME VARCHAR2(30) NOT NULL
);

CREATE TABLE CARD (
    CARD_ID             NUMBER(6,0) NOT NULL,
    CARD_NUMBER         NUMBER(16,0) NOT NULL,
    CVV                 NUMBER(3,0) NOT NULL,
    EXPIRATION_DATE     DATE NOT NULL,
    CONSTRAINT CARD_PK PRIMARY KEY (CARD_ID)
);

CREATE TABLE EMPLOYEE_TYPE(
    EMPLOYEE_TYPE       VARCHAR2(1) PRIMARY KEY,
    EMPLOYEE_TYPE_NAME  VARCHAR2(20) NOT NULL,
    SALARY              NUMBER(6,0) NOT NULL
);

CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID   NUMBER(6,0) PRIMARY KEY,
    FIRST_NAME    VARCHAR2(20) NOT NULL,
    MIDDLE_NAME   VARCHAR2(25) NOT NULL,
    LAST_NAME     VARCHAR2(25) NOT NULL,
    EMPLOYEE_TYPE VARCHAR2(1) NOT NULL,
    CONSTRAINT    EMPLOYEE_TYPE_FK FOREIGN KEY (EMPLOYEE_TYPE) REFERENCES EMPLOYEE_TYPE (EMPLOYEE_TYPE)
);

-- CREATE SEQUENCE EMPLOYEE_SEQ
-- START WITH 1
-- INCREMENT BY 1;

CREATE TABLE PRODUCTS (
    PRODUCT_ID      NUMBER(6,0) PRIMARY KEY,
    PRODUCT_NAME    VARCHAR2(50) NOT NULL,
    PRICE           NUMBER(6,0) NOT NULL
);

CREATE TABLE SERVICES (
    SERVICE_CODE    NUMBER(4,0) PRIMARY KEY,
    SERVICE_NAME    VARCHAR2(50) NOT NULL,
    DESCRIPTION     VARCHAR2(100),
    EMPLOYEE_TYPE   VARCHAR2(1) NOT NULL,
    PRODUCT_ID      NUMBER(6,0),
    PRICE           NUMBER(6,0) NOT NULL,
    CONSTRAINT SERVICES_FK1 FOREIGN KEY (EMPLOYEE_TYPE) REFERENCES EMPLOYEE_TYPE (EMPLOYEE_TYPE),
    CONSTRAINT SERVICES_FK2 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);

CREATE TABLE ROOM_TYPE_SERVICE (
    SERVICE_CODE        NUMBER(4,0) NOT NULL,
    ROOM_TYPE           VARCHAR2(1) NOT NULL,
    CONSTRAINT RTS_PK PRIMARY KEY (SERVICE_CODE, ROOM_TYPE),
    CONSTRAINT RTS_FK1 FOREIGN KEY (SERVICE_CODE) REFERENCES SERVICES (SERVICE_CODE),
    CONSTRAINT RTS_FK2 FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE (ROOM_TYPE)
);



CREATE TABLE BRN (
    BRN                 VARCHAR2(6) NOT NULL,
    PRIMARY_GUEST_ID    NUMBER(6,0) NOT NULL,
    BOOKING_DATE        DATE NOT NULL,
    CHECK_IN_DATE       DATE NOT NULL,
    CHECK_OUT_DATE      DATE,
    ROOM_TYPE           VARCHAR2(1) NOT NULL,
    NO_OF_ROOMS         NUMBER(2,0) NOT NULL,
    CONSTRAINT BRN_PK1 PRIMARY KEY (BRN),
    CONSTRAINT BRN_FK1 FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE (ROOM_TYPE),
    CONSTRAINT BRN_FK2 FOREIGN KEY (PRIMARY_GUEST_ID) REFERENCES GUEST (GUEST_ID)
);


CREATE TABLE BRN_GUEST (
    BRN                 VARCHAR2(6) NOT NULL,
    GUEST_ID            NUMBER(6,0) NOT NULL,
    CONSTRAINT BG_TABLE_PK PRIMARY KEY (BRN, GUEST_ID),
    CONSTRAINT BG_TABLE_FK1 FOREIGN KEY (BRN) REFERENCES BRN (BRN),
    CONSTRAINT BG_TABLE_FK2 FOREIGN KEY (GUEST_ID) REFERENCES GUEST (GUEST_ID)
);

CREATE TABLE ROOM (
    ROOM_NUMBER NUMBER(3, 0) PRIMARY KEY,
    ROOM_TYPE VARCHAR2(1) NOT NULL,
    CONSTRAINT ROOM_TYPE_FK FOREIGN KEY (ROOM_TYPE) REFERENCES ROOM_TYPE (ROOM_TYPE)
);

CREATE TABLE BRN_ROOMS (
    BRN                 VARCHAR2(6) NOT NULL,
    ROOM_NUMBER         NUMBER(3,0) NOT NULL,
    CONSTRAINT BR_TABLE_PK PRIMARY KEY (BRN, ROOM_NUMBER),
    CONSTRAINT BR_TABLE_FK1 FOREIGN KEY (BRN) REFERENCES BRN (BRN),
    CONSTRAINT BR_TABLE_FK2 FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM (ROOM_NUMBER)
);

CREATE TABLE BILL_PAYMENT (
    BP_ID               NUMBER(6,0) NOT NULL,
    BRN                 VARCHAR2(6) NOT NULL,
    TOTAL               NUMBER(6,0) NOT NULL,
    PAYMENT_METHOD      VARCHAR2(1),
    CARD_ID             NUMBER(6,0),
    CONSTRAINT BP_TABLE_PK PRIMARY KEY (BP_ID),
    CONSTRAINT BP_TABLE_FK1 FOREIGN KEY (BRN) REFERENCES BRN (BRN),
    CONSTRAINT BP_TABLE_FK2 FOREIGN KEY (CARD_ID) REFERENCES CARD (CARD_ID)
);

CREATE TABLE BRN_SERVICES (
    BRN             VARCHAR2(6) NOT NULL,
    ROOM_NUMBER     NUMBER(3,0),
    SERVICE_CODE    NUMBER(4,0) NOT NULL,
    CONSTRAINT BRN_S_PK PRIMARY KEY (BRN, SERVICE_CODE),
    CONSTRAINT BRN_S_FK1 FOREIGN KEY (BRN) REFERENCES BRN (BRN),
    CONSTRAINT BRN_S_FK2 FOREIGN KEY (ROOM_NUMBER) REFERENCES ROOM (ROOM_NUMBER),
    CONSTRAINT BRN_S_FK3 FOREIGN KEY (SERVICE_CODE) REFERENCES SERVICES (SERVICE_CODE)
);

-- CREATE SEQUENCE SERVICE_SEQ
-- START WITH 1
-- INCREMENT BY 1;

-- DROP TABLE BRN_SERVICES;
-- DROP TABLE BRN_ROOMS;
-- DROP TABLE BRN_GUEST;
-- DROP TABLE BILL_PAYMENT;
-- DROP TABLE BRN;
-- DROP TABLE SERVICES;
-- DROP TABLE ROOM;
-- DROP TABLE ROOM_TYPE_SERVICE;
-- DROP TABLE PRODUCTS;
-- DROP TABLE EMPLOYEE;
-- DROP TABLE EMPLOYEE_TYPE;
-- DROP TABLE CARD;
-- DROP TABLE BED_TYPE;
-- DROP TABLE ROOM_TYPE;
-- DROP TABLE GUEST;
-- DROP SEQUENCE EMPLOYEE_SEQ;
-- DROP SEQUENCE SERVICE_SEQ;
